language: python

sudo: false

python:
  - "2.7"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "nightly" # currently points to 3.7-dev

# command to install dependencies

install:
  - pip install --upgrade pip
  - pip install --upgrade .
  - pip install pyyaml
  - pip install tox
  - pip install --upgrade -r requirements.txt
  - pip install codecov

# command to run tests

script: tox
  - coverage run tests.py

after_success:
  - codecov
