language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install .
  - pip install tox-travis
  - pip install coverage
  - pip install codecov
# command to run tests
script: tox
